name: 发布NPM包

on:
  push:
    tags:
      - 'v*' # 当推送以v开头的标签时触发，如v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 运行Lint
        run: pnpm lint

      - name: 构建
        run: pnpm build

      - name: 发布
        if: success()
        run: |
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
